### ISSUE TITLE
Crash on startup 1.20.2

### ISSUE THREAD

**Issue by thewickening** [EnvyWare/ReforgedBingo#15]
`[09:06:46 INFO]: Found 1 dependencies adding them to mods collection
Exception in thread "main" java.lang.module.ResolutionException: Modules mysql.connector.j and reforgedbingo export package com.mysql.cj.protocol.a to module pixelmon
        at java.base/java.lang.module.Resolver.resolveFail(Resolver.java:901)
        at java.base/java.lang.module.Resolver.failTwoSuppliers(Resolver.java:815)
        at java.base/java.lang.module.Resolver.checkExportSuppliers(Resolver.java:736)
        at java.base/java.lang.module.Resolver.finish(Resolver.java:380)
        at java.base/java.lang.module.Configuration.<init>(Configuration.java:140)
        at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:494)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.1.1/cpw.mods.modlauncher.ModuleLayerHandler.buildLayer(ModuleLayerHandler.java:72)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.1.1/cpw.mods.modlauncher.TransformationServicesHandler.buildTransformingClassLoader(TransformationServicesHandler.java:47)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.1.1/cpw.mods.modlauncher.Launcher.run(Launcher.java:94)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.1.1/cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.1.1/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:13)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.1.1/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:10)
        at net.minecraftforge.bootstrap@1.2.0/net.minecraftforge.bootstrap.BootstrapLauncher.main(BootstrapLauncher.java:126)
        at com.mohistmc.MohistMCStart.main(MohistMCStart.java:106)
container@pterodactyl~ Server marked as offline...`

**Comment by danorris709** [comment]
I believe this is fixed in the next version

**Comment by thewickening** [comment]
> I believe this is fixed in the next version

If its the latest one you just released, its not fixed, same error. "MySQL only" it does work fine with json, same issue on stop/restart though.
https://pastebin.com/5cpzpKvF

Also this error spams when you stop/restart the server.
https://pastebin.com/Kw6MKvB2
